### ISSUE TITLE
Link option doesn't work on Rich Text Field in Query Counter app

### ISSUE THREAD

**Issue by kanserh** [RallyTechServices/query-counter#2]
When attempted to add a Link, the modal dialog box that pops up cannot be saved.  I can easily reproduce if needed.

**Comment by jmartin-rally** [comment]
I tried upgrading to 2.1 just to make sure it's not a legacy sdk issue, but the problem persists.  The RTE is a google component -- the modal dialog isn't in Ext, which might be what's causing the problem inside the settings dialog.  

Perhaps making it a button that launches the dialog will separate it from the settings fog.

**Comment by kanserh** [comment]
Thanks for looking into it John!  I believe people would be very happy with a button workaround.

**Comment by kcorkan** [comment]
Heather,  can you let me know if you still see this with the new version?  I was able to add a link.  The only issue that I see is if the link is not https and is clicked to open in the same window, the app throws a mixed content error.  If you open the link in a new tab, it opens without issue.

**Comment by kanserh** [comment]
I don't know when this got fixed, but it has been working for a while now.  No longer an issue.
