### ISSUE TITLE
Functionality Request - Add toggle to disable the query call to get a text only app

### ISSUE THREAD

**Issue by kanserh** [RallyTechServices/query-counter#3]
Often we use this app to simply show formatted text (without using the query part).  However, even with setting the query to something like "(ObjectID < 0)", if you have many of these on a dashboard (which we often do) the page is slow to load.   My hope is that such an app would help with the page load.  I can share many example of the usefulness of this if interested.

**Comment by jmartin-rally** [comment]
Heather, how would this be different from the Custom HTML app?

**Comment by kanserh** [comment]
In the custom HTML app you have to write HTML to get nice formatting.  In the query counter app, you get this nice rich text editor.  That is a huge difference for those of us that forget how to do things like lists in HTML.

**Comment by jmartin-rally** [comment]
Gotcha.  So it's an app that uses the rich text editor but no query.  We could just have a checkbox to turn the query off.  There's still a lot of overhead in an app that might be slow on a well-populated page because each and everyone downloads the sdk (I think).  It'd be interesting to write this then do a comparison with custom html to see how different the speeds are.

**Comment by kanserh** [comment]
![2017-08-02_16-10-27](https://user-images.githubusercontent.com/27898156/28892840-48b71380-779d-11e7-9cd1-38275dc34b72.png)

**Comment by kanserh** [comment]
This is an example, the two apps on the left dont show the result of the query but the query is still being called.    Yes, a toggle would work perfectly and be easier than a spinoff app.

**Comment by kcorkan** [comment]
@kanserh please take a look at the latest version.  I have added the ability to have no queries as requested.  If it looks ok, I'll close this out.

**Comment by kcorkan** [comment]
See https://github.com/RallyTechServices/rich-text-app for a rich text only app.
